### ISSUE TITLE
[AMBIENTE] Projeto inteiro não existe *1

### ISSUE THREAD

**Issue by EnzoWM02** [Huio-op/simple_events_app#1]
Cliente: Enzo (Interno)
Projeto: Any

## Descreva o problema

Não há projeto!

## Como simular o problema?

Sim.

## Solução sugerida

Fazer o projeto!

**Comment by Huio-op** [comment]
Pode anexar o log do erro?

**Comment by EnzoWM02** [comment]
Segue:

<details> <summary> LOG </summary>

```
deu erro
```

</details>
